// Generated by CoffeeScript 1.6.3
var Q,
  __slice = [].slice;

Q = require('q');

module.exports = function(fn) {
  return function() {
    var args, deferral;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    deferral = Q.defer();
    args.unshift(deferral);
    fn.apply(this, args);
    return deferral.promise;
  };
};
