// Generated by CoffeeScript 1.6.3
var Q;

Q = require('q');

module.exports = function(fn) {
  return function() {
    var deferral;
    deferral = Q.defer();
    fn.apply(this, arguments);
    return deferral.promise;
  };
};
