// Generated by CoffeeScript 1.6.3
module.exports = function(fn) {
  return function() {
    /* do*/

    var test;
    test = 1;
    (function(test) {
      return console.log(test);
    })(test);
    /* do*/

    return fn.call(this, arguments);
  };
};
